
all:
	make -C 1
	make -C 2
	make -C 3
	make -C 4
	make -C 5
	make -C 6
	make -C 7
	make -C 8
	make -C 9
	make -C 10
	make -C 11
	make -C 12
	make -C 13
	make -C 14
	make -C 15
	make -C 16
	make -C 17
	make -C 18
